from __future__ import annotations

import asyncio
import os
import re
import time
from dataclasses import asdict
from typing import Callable, Dict, List, Optional

import fitz

from pdf_tran_md.core.pdf_parser import build_chunks_for_sections, build_footnote_skeletons
from pdf_tran_md.models import Chunk, JobConfig, Section, TranslationSettings, TranslationState, STATE_VERSION
from pdf_tran_md.services.api_client import APIError, OpenAICompatibleClient
from pdf_tran_md.services.exporter import export_markdown_to_pdf
from pdf_tran_md.services.storage import StateStore, ensure_utf8_write


def markdown_heading(level: int, title: str) -> str:
    return f"{'#' * min(max(level, 1), 6)} {title}"


def format_seconds(sec: float) -> str:
    sec = max(0, int(sec))
    h = sec // 3600
    m = (sec % 3600) // 60
    s = sec % 60
    if h > 0:
        return f"{h}h {m}m {s}s"
    if m > 0:
        return f"{m}m {s}s"
    return f"{s}s"


class RateLimiter:
    def __init__(self, min_interval: float):
        self.min_interval = max(0.0, min_interval)
        self._lock = asyncio.Lock()
        self._next_time = 0.0

    async def wait(self) -> None:
        if self.min_interval <= 0:
            return
        async with self._lock:
            now = time.monotonic()
            wait_time = max(0.0, self._next_time - now)
            if wait_time > 0:
                await asyncio.sleep(wait_time)
            self._next_time = max(self._next_time, time.monotonic()) + self.min_interval

    async def penalize(self, seconds: float) -> None:
        async with self._lock:
            self._next_time = max(self._next_time, time.monotonic() + max(0.0, seconds))


class TranslationRunner:
    def __init__(
        self,
        state_store: Optional[StateStore] = None,
        log_callback: Optional[Callable[[str], None]] = None,
        status_callback: Optional[Callable[[str], None]] = None,
        progress_callback: Optional[Callable[[int, int, float, float], None]] = None,
    ):
        self.state_store = state_store or StateStore()
        self.log_callback = log_callback or (lambda message: None)
        self.status_callback = status_callback or (lambda message: None)
        self.progress_callback = progress_callback or (lambda current, total, percent, eta: None)
        self.stop_requested = False

    def log(self, message: str) -> None:
        self.log_callback(message)

    def set_status(self, message: str) -> None:
        self.status_callback(message)

    def request_stop(self) -> None:
        self.stop_requested = True

    def create_state(self, job: JobConfig) -> TranslationState:
        doc = fitz.open(job.pdf_path)
        try:
            selected_sections = [Section(**section) for section in job.selected_sections]
            settings = TranslationSettings(**job.settings)
            if settings.enhance_markdown:
                footnote_skeletons, footnote_numbers, page_cutoffs = build_footnote_skeletons(
                    doc, selected_sections
                )
            else:
                footnote_skeletons = {}
                footnote_numbers = None
                page_cutoffs = None
            page_markers = {int(page_no) for page_no in footnote_skeletons} if footnote_skeletons else None
            chunks = build_chunks_for_sections(
                doc,
                selected_sections,
                max_chars=5000,
                page_markers=page_markers,
                page_footnote_numbers=footnote_numbers,
                page_cutoffs=page_cutoffs,
            )
        finally:
            doc.close()

        if not chunks:
            raise RuntimeError(f"未提取到可翻译文本：{job.pdf_path}")

        return TranslationState(
            version=STATE_VERSION,
            pdf_path=os.path.abspath(job.pdf_path),
            output_path=os.path.abspath(job.output_path),
            settings=job.settings,
            translate_mode=job.translate_mode,
            selected_section_indices=[section["index"] for section in job.selected_sections],
            chunks=[asdict(chunk) for chunk in chunks],
            footnote_skeletons=footnote_skeletons,
            completed_translations={},
            written_chunk_ids=[],
            export_pdf=job.export_pdf,
            pdf_output_path=os.path.abspath(job.pdf_output_path) if job.pdf_output_path else "",
            markdown_header_written=False,
            started_at=time.time(),
        )

    def write_markdown_header_if_needed(self, state: TranslationState) -> None:
        if state.markdown_header_written:
            return
        settings = TranslationSettings(**state.settings)
        header = "\n".join(
            [
                "<!-- Generated by PDF Translator -->",
                "",
                "# 翻译结果",
                "",
                f"- 原 PDF：`{state.pdf_path}`",
                f"- 模型：`{settings.model}`",
                f"- 目标语言：`{settings.target_language}`",
                f"- 翻译范围：`{'全文' if state.translate_mode == 'all' else '仅所选章节'}`",
                "",
                "---",
                "",
            ]
        )
        ensure_utf8_write(state.output_path, header, mode="w")
        state.markdown_header_written = True
        self.state_store.save(state)

    def append_chunk_translation(
        self,
        state: TranslationState,
        chunk: Chunk,
        translated_text: str,
        section_heading_written: Dict[int, bool],
    ) -> None:
        parts: List[str] = []
        if not section_heading_written.get(chunk.section_index, False):
            parts.extend([markdown_heading(chunk.section_level, chunk.section_title), ""])
            section_heading_written[chunk.section_index] = True

        parts.extend([translated_text.strip(), "", ""])
        ensure_utf8_write(state.output_path, "\n".join(parts), mode="a")

    async def _translate_chunk(
        self,
        client: OpenAICompatibleClient,
        limiter: RateLimiter,
        chunk: Chunk,
        total: int,
        position: int,
        *,
        apply_cleanup: bool = True,
    ) -> str:
        max_attempts = 3
        for attempt in range(1, max_attempts + 1):
            await limiter.wait()
            self.set_status(f"正在翻译第 {position}/{total} 个文本块")
            self.log(
                f"[进行中] chunk {position}/{total} | 章节：{chunk.section_title} | 页码：{chunk.start_page}-{chunk.end_page}"
            )
            start = time.time()
            try:
                translated = await client.translate(chunk.source_text, apply_cleanup=apply_cleanup)
                elapsed = time.time() - start
                self.log(f"[完成] chunk {position}/{total} | 单块耗时：{elapsed:.1f}s")
                return translated
            except APIError as exc:
                if "HTTP 状态码: 429" not in str(exc) or attempt == max_attempts:
                    raise
                match = re.search(r"Retry-After: ([0-9.]+)", str(exc))
                cooldown = float(match.group(1)) if match else 3.0 * attempt
                await limiter.penalize(cooldown)
                self.log(
                    f"[限流] chunk {position}/{total} 第 {attempt} 次触发 429，"
                    f"将在 {cooldown:.1f}s 后重试。"
                )
        raise RuntimeError("unreachable")

    async def run_state(self, state: TranslationState) -> None:
        settings = TranslationSettings(**state.settings)
        client = OpenAICompatibleClient(settings)
        limiter = RateLimiter(settings.min_request_interval)

        chunks = [Chunk(**item) for item in state.chunks]
        total = len(chunks)
        if total == 0:
            raise RuntimeError("没有可翻译的文本块。")

        self.write_markdown_header_if_needed(state)

        written_chunk_ids = set(state.written_chunk_ids)
        completed_ids = {int(chunk_id) for chunk_id in state.completed_translations}
        section_heading_written: Dict[int, bool] = {}
        for chunk_id in written_chunk_ids:
            if 0 <= chunk_id < len(chunks):
                section_heading_written[chunks[chunk_id].section_index] = True

        next_write_id = 0
        while next_write_id in written_chunk_ids:
            next_write_id += 1

        def flush_ready_chunks() -> None:
            nonlocal next_write_id
            while next_write_id < total and str(next_write_id) in state.completed_translations:
                chunk = chunks[next_write_id]
                if next_write_id not in written_chunk_ids:
                    self.append_chunk_translation(
                        state,
                        chunk,
                        state.completed_translations[str(next_write_id)],
                        section_heading_written,
                    )
                    state.written_chunk_ids.append(next_write_id)
                    written_chunk_ids.add(next_write_id)
                    self.state_store.save(state)
                next_write_id += 1

        flush_ready_chunks()

        pending_chunks = [chunk for chunk in chunks if chunk.chunk_id not in completed_ids]
        in_flight: Dict[asyncio.Task[str], Chunk] = {}

        while (pending_chunks or in_flight) and not self.stop_requested:
            while pending_chunks and len(in_flight) < max(1, settings.max_concurrency) and not self.stop_requested:
                chunk = pending_chunks.pop(0)
                task = asyncio.create_task(
                    self._translate_chunk(
                        client,
                        limiter,
                        chunk,
                        total,
                        chunk.chunk_id + 1,
                        apply_cleanup=True,
                    )
                )
                in_flight[task] = chunk

            if not in_flight:
                break

            done, _ = await asyncio.wait(in_flight.keys(), return_when=asyncio.FIRST_COMPLETED)
            for task in done:
                chunk = in_flight.pop(task)
                translated = task.result()
                state.completed_translations[str(chunk.chunk_id)] = translated
                self.state_store.save(state)
                flush_ready_chunks()

                completed = len(state.completed_translations)
                percent = completed / total * 100
                avg = (time.time() - state.started_at) / completed if completed else 0
                eta = avg * (total - completed)
                self.progress_callback(completed, total, percent, eta)

        if self.stop_requested:
            for task in list(in_flight):
                task.cancel()
            if in_flight:
                await asyncio.gather(*in_flight.keys(), return_exceptions=True)
            self.log("用户已请求停止。")
            self.set_status("已停止，可稍后从断点继续。")
            return

        flush_ready_chunks()
        if len(state.completed_translations) == total:
            await self._translate_and_insert_footnotes(state, client, limiter)
            self.set_status("翻译完成")
            self.log("全部翻译完成，正在清理断点文件。")
            if state.export_pdf and state.pdf_output_path:
                self.set_status("翻译完成，正在导出 PDF")
                export_markdown_to_pdf(state.output_path, state.pdf_output_path)
                self.log(f"PDF 导出完成：{state.pdf_output_path}")
            self.state_store.clear(state.output_path)
            self.log(f"输出完成：{state.output_path}")
        else:
            self.log("翻译未全部完成，断点已保留，可稍后继续。")

    async def _translate_and_insert_footnotes(
        self,
        state: TranslationState,
        client: OpenAICompatibleClient,
        limiter: RateLimiter,
    ) -> None:
        if not state.footnote_skeletons:
            return

        translated_pages: Dict[int, List[str]] = {}

        for page_no in sorted(state.footnote_skeletons, key=lambda x: int(x)):
            notes = state.footnote_skeletons[page_no]
            if not notes:
                continue
            self.set_status(f"翻译脚注：第 {page_no} 页")
            await limiter.wait()
            translated = await client.translate("\n".join(notes), apply_cleanup=False)
            translated_pages[int(page_no)] = self._format_translated_footnotes(translated)

        if not translated_pages:
            return

        with open(state.output_path, "r", encoding="utf-8") as file:
            content = file.read()

        missing_pages: List[int] = []
        for page_no, lines in translated_pages.items():
            marker = f"[[PAGE:{page_no}]]"
            if marker in content:
                block = "\n\n".join(["<!-- PAGE:{} FOOTNOTES -->".format(page_no)] + lines)
                content = content.replace(marker, block)
            else:
                missing_pages.append(page_no)

        if missing_pages:
            parts = ["", "---", "", "## 脚注（按页）", ""]
            for page_no in missing_pages:
                parts.append(f"### 第 {page_no} 页")
                parts.extend(translated_pages[page_no])
                parts.append("")
            content += "\n".join(parts)

        content = re.sub(r"\[\[PAGE:\d+\]\]", "", content)
        ensure_utf8_write(state.output_path, content, mode="w")

    @staticmethod
    def _format_translated_footnotes(text: str) -> List[str]:
        lines: List[str] = []
        for raw in text.splitlines():
            line = raw.strip()
            if not line:
                continue
            line = re.sub(r"^\s*\[\[FN(\d+)\]\]\s*:?\s*", r"[^\1]: ", line)
            if not re.match(r"^\[\^\d+\]:", line):
                line = f"- {line}"
            lines.append(line)
        return lines
